name: BlockDisplayCreator
author: General_Breddok
version: '${project.version}'
main: me.general_breddok.blockdisplaycreator.BlockDisplayCreator
api-version: 1.19
description: Plugin for creating and fully customizing custom blocks
website: https://www.spigotmc.org/resources/blockdisplaycreator.114877/

softdepend: [ PlaceholderAPI, WorldGuard, PacketEvents, SuperiorSkyblock2 ]

loadbefore:
  - SuperiorSkyblock2

commands:
  blockdisplaycreator:
    description: Main command for BlockDisplayCreator (1.19.4 only)
    usage: /bdc <custom-block|reload|erase>
    aliases: [bdc]



permissions:
  blockdisplaycreator.blocks-destruction:
    description: Allows players to destroy custom blocks even if blocks-destruction is set to false
    default: op

  blockdisplaycreator.blocks-placement:
    description: Allows players to place custom blocks even if blocks-placement is set to false
    default: op

  blockdisplaycreator.blocks-interaction:
    description: Allows players to interact with custom blocks even if blocks-interaction is set to false
    default: op

  bdc.bypass.*:
    description: Allows players to bypass region and island checks for custom blocks
    default: op
    children:
      bdc.bypass.wg: true
      bdc.bypass.skyblock: true

  bdc.bypass.wg:
    description: Allows players to bypass WorldGuard region checks for custom blocks
    default: op

  bdc.bypass.skyblock:
    description: Allows players to bypass SuperiorSkyblock2 island checks for custom blocks
    default: op

  bdc.quickselect.creative:
    description: Allows players in creative to get custom blocks that they don't have in their inventory using quick select
    default: op

  bdc.command.*:
    description: Allows players to use all BlockDisplayCreator commands
    default: op
    children:
      bdc.command.custom-block: true
      bdc.command.reload: true
      bdc.command.erasecbdata: true


  bdc.command.custom-block.*:
    description: Allows players to use /bdc custom-block command
    default: op
    children:
      bdc.command.custom-block.give: true
      bdc.command.custom-block.place: true
      bdc.command.custom-block.break: true
      bdc.command.custom-block.editfile: true

  bdc.command.custom-block.give:
    description: Allows players to use /bdc custom-block give command
    default: op

  bdc.command.custom-block.place:
    description: Allows players to use /bdc custom-block place command
    default: op

  bdc.command.custom-block.break:
    description: Allows players to use /bdc custom-block break command
    default: op

  bdc.command.custom-block.editfile:
    description: Allows players to use /bdc custom-block editfile command
    default: op

  bdc.command.reload:
    description: Allows players to use /bdc reload command
    default: op

  bdc.command.erasecbdata:
    description: Allows players to use /bdc erasecbdata command to remove custom block data and entities
    default: op


