name: BlockDisplayCreator
author: General_Breddok
version: '${project.version}'
main: me.general_breddok.blockdisplaycreator.BlockDisplayCreator
api-version: 1.19
description: Plugin for creating and fully customizing custom blocks

softdepend: [ PlaceholderAPI, WorldGuard ]

commands:
  blockdisplaycreator:
    description: Main command for BlockDisplayCreator
    usage: /bdc <custom-block|reload|killcbentities>
    aliases: [bdc]



permissions:
  blockdisplaycreator.blocks-destruction:
    description: Allows players to destroy custom blocks even if blocks-destruction is set to false
    default: op

  blockdisplaycreator.blocks-placement:
    description: Allows players to place custom blocks even if blocks-placement is set to false
    default: op

  blockdisplaycreator.blocks-interaction:
    description: Allows players to interact with custom blocks even if blocks-interaction is set to false
    default: op

  bdc.bypass.wg:
    description: Allows players to bypass WorldGuard region checks for custom blocks
    default: op
    description: Allows bypassing WorldGuard region checks

  bdc.command.custom-block:
    description: Allows players to use the custom-block command
    default: op
    description: Allows giving a custom block to a player

  bdc.command.reload:
    description: Allows players to reload the plugin configuration
    default: op
    description: Allows reloading the plugin configuration

  bdc.command.killcbentities:
    description: Allows players to use the killcbentities command to remove custom block entities
    default: op
    description: Allows killing all custom block entities

